server:
  port: 8085
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/bibliotecadb
    username: root
 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        

  application:
    name: 'biblioteca'
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka